parameters:
    temp_upload_dir: '%kernel.project_dir%/var/perscom/uploads/'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Forumify\PerscomPlugin\:
        resource: '../src/'
        exclude:
            - '../src/**/DataFixture/'
            - '../src/**/DependencyInjection/'
            - '../src/**/Entity/'

    Forumify\PerscomPlugin\Admin\Controller\UserEditController:
        arguments:
            $tempUploadDir: '%temp_upload_dir%'
